### ISSUE TITLE
关于获取IPV6网关的问题

### ISSUE THREAD

**Issue by openMJJ** [oneclickvirt/oneclickvirt.github.io#1]
Proxmox VE安装过程总是无法获取IPV6的网关。
 ##ip -6 route show 
::1 dev lo proto kernel metric 256 pref medium
2406:ef80:2:ea8b::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
default via fe80::1 dev eth0 metric 1024 onlink pref medium

代码进行了如下修复：
#!/bin/bash

# 检查所有默认IPv6网关的可达性
check_ipv6_gateway() {
    local gateways=$(ip -6 route show | awk '/default via/{print $3}')
    
    for gateway in $gateways; do
        if ping -c 1 -6 -W 3 $gateway >/dev/null 2>&1; then
            echo "IPv6 gateway $gateway is reachable."
            return 0
        fi
    done
    
    echo "IPv6 gateway is not reachable. Setting to empty."
    echo "" >/usr/local/bin/pve_ipv6_gateway
    return 1
}

if [ ! -f /usr/local/bin/pve_ipv6_gateway ] || [ ! -s /usr/local/bin/pve_ipv6_gateway ] || [ "$(sed -e '/^[[:space:]]*$/d' /usr/local/bin/pve_ipv6_gateway)" = "" ]; then
    check_ipv6_gateway
fi

ipv6_gateway=$(cat /usr/local/bin/pve_ipv6_gateway)

目前还是无法实现识别IPV6，请大佬帮忙优化代码。

**Comment by spiritLHLS** [comment]
请在对应仓库开设对应问题，并附上对应仓库issues要求的日志查询等内容
