### ISSUE TITLE
疑似开LXC小鸡时下载有错

### ISSUE THREAD

**Issue by hkwwwxxx** [oneclickvirt/oneclickvirt.github.io#3]
### 在Oracle Cloud日本的ARM机ubuntu20.04上用普通批量的方式开lxc，出错如下图，最后能成功开出小鸡。这些错误估计是程序自动获取到了母鸡的内网IPv6地址，于是路由到了IPv6去了下载了，建议去掉开头的那个CDN检测。另外开小鸡结束的时候也总Error: The device already exists

![Snipaste_2023-12-21_07-37-23](https://github.com/oneclickvirt/oneclickvirt.github.io/assets/153110911/60f7a59e-76da-4bce-a205-53b2bb9fd67e)

![Snipaste_2023-12-21_07-40-57](https://github.com/oneclickvirt/oneclickvirt.github.io/assets/153110911/c00cf2de-ea35-4a53-b087-ad00de7bc475)

![Snipaste_2023-12-21_07-54-12](https://github.com/oneclickvirt/oneclickvirt.github.io/assets/153110911/5c7ba34f-d0fe-4858-aca1-e34ccbe4ca57)

**Comment by spiritLHLS** [comment]
开设过程中你是否选择了IPV6启用？这可能是设置问题，晚些时候我测试一下吧，还有，有问题请去对应仓库的issues反馈

**Comment by spiritLHLS** [comment]
已尝试修复

**Comment by hkwwwxxx** [comment]
[https://www.spiritlhl.net/guide/lxd_precheck.html](url)
### 不好意思，这个说明文档的右上角的github链接直接把我带到这里就直接发ISSUSE，没注意看仓库名。刚进到LXD仓库里好像没有看到ISSUES哦，不太会用github。
### 开设过程选不选IPv6都还是有错，不过结尾没错了，很久前用就发现这个问题的，这次我怕忘了所以提一下，慢慢改就好。谢谢开发贡献！

![Snipaste_2023-12-22_06-21-13](https://github.com/oneclickvirt/oneclickvirt.github.io/assets/153110911/b503d2bb-65d9-43de-9db1-2c14f9b73fcd)
![Snipaste_2023-12-22_07-03-25](https://github.com/oneclickvirt/oneclickvirt.github.io/assets/153110911/4eecd4b6-ec39-4481-b243-49fb144f1141)
![Snipaste_2023-12-22_07-00-22](https://github.com/oneclickvirt/oneclickvirt.github.io/assets/153110911/39b434ed-0c58-4cd0-985d-373e314e611c)

**Comment by spiritLHLS** [comment]
这个显示是正常的，容器刚启动时网络未启动，这个动作不会导致任何东西下载失败，后续有判断进行fix
