### ISSUE TITLE
自动配置宿主机的网关执行后，提示“Can not find 'auto lo' in /etc/network/interface”

### ISSUE THREAD

**Issue by ziyou2** [oneclickvirt/oneclickvirt.github.io#7]
Locale set to C.utf8
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libxdp1 openvswitch-common python3-openvswitch python3-sortedcontainers uuid-runtime
Suggested packages:
  openvswitch-doc python-sortedcontainers-doc
The following NEW packages will be installed:
  libxdp1 openvswitch-common openvswitch-switch python3-openvswitch python3-sortedcontainers uuid-runtime
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 4417 kB of archives.
After this operation, 25.8 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main arm64 libxdp1 arm64 1.3.1-1 [55.0 kB]
Get:2 http://deb.debian.org/debian bookworm/main arm64 openvswitch-common arm64 3.1.0-2 [1831 kB]
Get:3 http://deb.debian.org/debian bookworm/main arm64 python3-sortedcontainers all 2.4.0-2 [31.9 kB]
Get:4 http://deb.debian.org/debian bookworm/main arm64 python3-openvswitch arm64 3.1.0-2 [864 kB]
Get:5 http://deb.debian.org/debian bookworm/main arm64 uuid-runtime arm64 2.38.1-5+b1 [50.7 kB]
Get:6 http://deb.debian.org/debian bookworm/main arm64 openvswitch-switch arm64 3.1.0-2 [1585 kB]
Fetched 4417 kB in 0s (12.1 MB/s)            
Selecting previously unselected package libxdp1:arm64.
(Reading database ... 55805 files and directories currently installed.)
Preparing to unpack .../0-libxdp1_1.3.1-1_arm64.deb ...
Unpacking libxdp1:arm64 (1.3.1-1) ...
Selecting previously unselected package openvswitch-common.
Preparing to unpack .../1-openvswitch-common_3.1.0-2_arm64.deb ...
Unpacking openvswitch-common (3.1.0-2) ...
Selecting previously unselected package python3-sortedcontainers.
Preparing to unpack .../2-python3-sortedcontainers_2.4.0-2_all.deb ...
Unpacking python3-sortedcontainers (2.4.0-2) ...
Selecting previously unselected package python3-openvswitch.
Preparing to unpack .../3-python3-openvswitch_3.1.0-2_arm64.deb ...
Unpacking python3-openvswitch (3.1.0-2) ...
Selecting previously unselected package uuid-runtime.
Preparing to unpack .../4-uuid-runtime_2.38.1-5+b1_arm64.deb ...
Unpacking uuid-runtime (2.38.1-5+b1) ...
Selecting previously unselected package openvswitch-switch.
Preparing to unpack .../5-openvswitch-switch_3.1.0-2_arm64.deb ...
Unpacking openvswitch-switch (3.1.0-2) ...
Setting up python3-sortedcontainers (2.4.0-2) ...
Setting up libxdp1:arm64 (1.3.1-1) ...
Setting up uuid-runtime (2.38.1-5+b1) ...
Adding group `uuidd' (GID 118) ...
Done.
Created symlink /etc/systemd/system/sockets.target.wants/uuidd.socket → /lib/systemd/system/uuidd.socket.
uuidd.service is a disabled or a static unit, not starting it.
Setting up openvswitch-common (3.1.0-2) ...
Setting up python3-openvswitch (3.1.0-2) ...
Setting up openvswitch-switch (3.1.0-2) ...
update-alternatives: using /usr/lib/openvswitch-switch/ovs-vswitchd to provide /usr/sbin/ovs-vswitchd (ovs-vswitchd) in auto mode
Created symlink /etc/systemd/system/openvswitch-switch.service.requires/ovs-record-hostname.service → /lib/systemd/system/ovs-record-hostname.service.
Created symlink /etc/systemd/system/multi-user.target.wants/openvswitch-switch.service → /lib/systemd/system/openvswitch-switch.service.
Processing triggers for libc-bin (2.36-9+deb12u4) ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
net-tools is already the newest version (2.10-0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
curl: (28) Connection timed out after 5001 milliseconds
curl: (28) Connection timed out after 5001 milliseconds
CDN available, using CDN
grep: /etc/network/interfaces: No such file or directory
--2024-02-08 08:59:38--  https://cdn0.spiritlhl.top/https://github.com/spiritLHLS/pve/releases/download/ndpresponder_aarch64/ndpresponder
Resolving cdn0.spiritlhl.top (cdn0.spiritlhl.top)... 172.67.208.154, 104.21.66.226
Connecting to cdn0.spiritlhl.top (cdn0.spiritlhl.top)|172.67.208.154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14026000 (13M) [application/octet-stream]
Saving to: ‘/usr/local/bin/ndpresponder’

/usr/local/bin/ndpresponder                                         100%[=================================================================================================================================================================>]  13.38M  --.-KB/s    in 0.07s   

2024-02-08 08:59:39 (179 MB/s) - ‘/usr/local/bin/ndpresponder’ saved [14026000/14026000]

--2024-02-08 08:59:39--  https://cdn0.spiritlhl.top/https://raw.githubusercontent.com/spiritLHLS/pve/main/extra_scripts/ndpresponder.service
Resolving cdn0.spiritlhl.top (cdn0.spiritlhl.top)... 104.21.66.226, 172.67.208.154
Connecting to cdn0.spiritlhl.top (cdn0.spiritlhl.top)|104.21.66.226|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘/etc/systemd/system/ndpresponder.service’

/etc/systemd/system/ndpresponder.service                                [ <=>                                                                                                                                                              ]     217  --.-KB/s    in 0s      

2024-02-08 08:59:40 (4.75 MB/s) - ‘/etc/systemd/system/ndpresponder.service’ saved [217]

chattr: No such file or directory while trying to stat /etc/network/interfaces
grep: /etc/network/interfaces: No such file or directory
Can not find 'auto lo' in /etc/network/interfaces

**Comment by spiritLHLS** [comment]
请查看 https://github.com/spiritLHLS/pve 对应issues的要求
