### ISSUE TITLE
使用incus部署的lxc虚拟鸡 搭3X-UI 端口不通

### ISSUE THREAD

**Issue by 15976770947** [oneclickvirt/oneclickvirt.github.io#8]
很奇怪换了很多系统 我用老版本 x ui成功了  可以麻烦大佬看一下吗 https://github.com/MHSanaei/3x-ui?tab=readme-ov-file

**Comment by spiritLHLS** [comment]
你没贴日志和所用的宿主机系统和开设的小鸡的系统，无法有效识别BUG，请张贴日志和对应信息

**Comment by spiritLHLS** [comment]
还有如果有问题麻烦到对应项目的issues提问，而不是在说明文档这里提问 https://github.com/oneclickvirt/incus
